Added changes to help debugging
D-Triveni/sdk-nrf pull request #4
Opened 2022-11-11 12:18 UTC by D-Triveni

Signed-off-by: Triveni D <triveni.danda@nordicsemi.no>

2022-11-14 12:39 UTC, krish2718 requested changes

2022-11-14 12:39 UTC, krish2718 commented on samples/wifi/sta/Kconfig
> +	default 8192
Why so high, just 32/64 should be enough.

2022-11-14 12:39 UTC, krish2718 commented on samples/wifi/sta/src/main.c
> +	for (i = 0; i < 100; i++) {
make this configurable, CONECTION_TIMEOUT_MS and then STATUS_POLLING_MS

2022-11-14 12:39 UTC, krish2718 commented on samples/wifi/sta/src/main.c
> +			context.connected = true;
what about failure case? If you get a failure then there is no point in polling status.

2022-11-14 12:39 UTC, krish2718 commented on samples/wifi/sta/src/main.c
> +		k_sleep(K_SECONDS(30));
what about waiting for DHCP event as we do print the IP

2022-11-14 12:50 UTC, krish2718 commented on samples/wifi/sta/src/main.c
> +		0);
0 is no delay, so, thread starts immediately, you should use K_FOREVER as you are starting the thread explicityl

2022-11-14 13:02 UTC, D-Triveni commented on samples/wifi/sta/src/main.c
> +			context.connected = true;
> what about failure case? If you get a failure then there is no point in polling status.

@krish2718  In the failure case, it will poll for 30sec and prints connection timeout.

2022-11-14 13:11 UTC, krish2718 commented on samples/wifi/sta/src/main.c
> +			context.connected = true;
but why, wpa_supplicant already sent failure up (this won't happen as connect timeout is 0, but still), so, we should consider connection complete.

2022-11-15 09:02 UTC, sr1dh48r approved these changes
Fine for most part. I would suggest using os timers to handle timeout scenarios in the future (uneless it was intentionally not used).

2022-11-15 11:19 UTC, sr1dh48r approved these changes

2022-11-21 12:01 UTC, bama-nordic approved these changes
LGTM

2022-11-21 12:01 UTC, bama-nordic commented on samples/wifi/sta/src/main.c
> +		if (k_sem_take(&sem_dhcp, K_SECONDS(70)) == -EAGAIN)
Need to add braces even for single-statement if

2022-11-29 10:23 UTC, closed without merging