SHEL-1249: samples: wifi: scan: Fix Kconfig options
D-Triveni/sdk-nrf pull request #6
Opened 2023-02-10 09:47 UTC by D-Triveni

Removed unnecessary Kconfig options from Scan sample

Signed-off-by: Triveni Danda <triveni.danda@nordicsemi.no>

2023-02-10 10:49 UTC, krish2718 requested changes

2023-02-10 10:49 UTC, krish2718 commented on samples/wifi/scan/prj.conf
>  CONFIG_MAIN_STACK_SIZE=4096
can you check if this can be reduced?

2023-02-10 10:49 UTC, krish2718 commented on samples/wifi/scan/prj.conf
>  CONFIG_NEWLIB_LIBC_NANO=n
I guess without the supplicant we can get this working with nano, its much smaller form factor.

2023-02-10 10:49 UTC, krish2718 commented on samples/wifi/scan/prj.conf
>  CONFIG_NETWORKING=y
you don't need the full networking stack, so, CONFIG_NET_NATIVE=n should do

2023-02-10 12:01 UTC, D-Triveni commented on samples/wifi/scan/prj.conf
>  CONFIG_MAIN_STACK_SIZE=4096
> can you check if this can be reduced?

Can be reduced to 2048.

2023-02-10 12:03 UTC, D-Triveni commented on samples/wifi/scan/prj.conf
>  CONFIG_NETWORKING=y
Seeing compilation issues after adding CONFIG_NET_NATIVE kconfig. So once this is fixed in driver, will add.

2023-02-15 07:48 UTC, krish2718 approved these changes
Commit log can be:

```
Remove unnecessary Kconfig options to reduce memory.

Observed the Flash and RAM usage reduction by approx. 
55 KB and 10KB respectively.
```

2023-02-15 12:08 UTC, closed without merging

2023-02-15 12:09 UTC, D-Triveni commented
As changes are finalized, closing.